# File: cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build container image'
    args:
      [
        'build',
        '.',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/cds-repo/train:latest',
        '-f',
        'dockerfiles/train.dockerfile'
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push container image'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/cds-repo/train:latest'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
